### ISSUE TITLE
Larger cropping res?

### ISSUE THREAD

**Issue by ghostCodeSpec** [city96/dataset-webui#6]
I used your dataset manager to help make an SD1.5 lora. It was easy enough, but I have one request: 

Is there any way to increase the cropping/upscaling resolution to 1024x1024? 

I want to try training an SDXL lora, but I believe my dataset would have to be 1024x1024.

**Comment by city96** [comment]
You can select 1024x1024 on the "Output" tab under resolution, or do you mean something else?

![image](https://github.com/user-attachments/assets/6e8f1e8e-6406-4339-8c48-c5bcb8910009)

**Comment by ghostCodeSpec** [comment]
I see it now, thanks. I thought the resolution was locked to 512, disregard.
